#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\script\mgt\fighterConst.py
COMMAND_ORBIT = 'ORBIT'
COMMAND_STOP = 'STOP'
COMMAND_GOTO_POINT = 'GOTO_POINT'
COMMAND_KAMIKAZE = 'KAMIKAZE'
TUBE_STATE_EMPTY = 'EMPTY'
TUBE_STATE_LOADING = 'LOADING'
TUBE_STATE_READY = 'READY'
TUBE_STATE_UNLOADING = 'UNLOADING'
TUBE_STATE_LAUNCHING = 'LAUNCHING'
TUBE_STATE_INSPACE = 'INSPACE'
TUBE_STATE_SCOOPING = 'SCOOPING'
COLOR_RETURNING = (1.0, 0.93, 0.51)
COLOR_INSPACE = (0.46, 0.84, 1.0)
COLOR_OPEN = (0.62, 0.62, 0.62)
COLOR_READY = (0.52, 0.97, 0.34)
COLOR_BY_STATE = {TUBE_STATE_EMPTY: COLOR_OPEN,
 TUBE_STATE_LOADING: COLOR_OPEN,
 TUBE_STATE_READY: COLOR_READY,
 TUBE_STATE_UNLOADING: COLOR_OPEN,
 TUBE_STATE_LAUNCHING: COLOR_OPEN,
 TUBE_STATE_INSPACE: COLOR_INSPACE,
 TUBE_STATE_SCOOPING: COLOR_RETURNING}
LABEL_BY_STATE = {TUBE_STATE_EMPTY: 'UI/Inventory/Fighters/Open',
 TUBE_STATE_LOADING: 'UI/Inventory/Fighters/Loading',
 TUBE_STATE_READY: 'UI/Inventory/Fighters/Ready',
 TUBE_STATE_UNLOADING: 'UI/Inventory/Fighters/Loading',
 TUBE_STATE_LAUNCHING: 'UI/Inventory/Fighters/Loading',
 TUBE_STATE_INSPACE: 'UI/Inventory/Fighters/InSpace',
 TUBE_STATE_SCOOPING: 'UI/Inventory/Fighters/Returning'}
HEALTHY_FIGTHER = (0.83, 0.92, 1.0, 1.0)
DAMAGED_FIGTHER = (0.42, 0.46, 0.5, 1.0)
LOADING_FIGHTER = (0.47, 0.75, 0.26, 1.0)
DEAD_FIGHTER = (0, 0, 0, 1)
ABILITY_ATTACK = 1
ABILITY_WEBS = 2
ABILITY_TARGET_PAINT = 3
ABILITY_MICROWARPDRIVE = 4
ABILITY_MICRO_JUMP_DRIVE = 5
ABILITY_DAMAGE_BOOST = 6
ABILITY_LAUNCH_BOMB = 7
