#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\evecamera\__init__.py
PRIORITY_NONE = 0
PRIORITY_LOW = 1
PRIORITY_NORMAL = 2
PRIORITY_HIGH = 3
FOV_MIN = 0.05
FOV_MAX = 1.0
DEFAULT_MAX_SPEED = 0.07
DEFAULT_FRICTION = 7.0
DEFAULT_FRONT_CLIP = 6.0
DEFAULT_BACK_CLIP = 10000000.0
DEFAULT_IDLE_SCALE = 0.65
LOOKATRANGE_MAX = 100000.0
LOOKATRANGE_MAX_NEW = 2000000.0
CAM_SPACE_PRIMARY = 'default'
CAM_SHIPORBIT = 'shiporbit'
CAM_SYSTEMMAP = 'systemmap'
CAM_STARMAP = 'starmap'
CAM_PLANET = 'planet'
CAM_HANGAR = 'hangar'
CAM_DUNGEONEDIT = 'dungeoneditor'
CAM_TACTICAL = 'tactical'
CAM_SHIPPOV = 'pov'
CAM_FARLOOK = 'farlook'
INSPACE_CAMERAS = (CAM_SPACE_PRIMARY,
 CAM_SHIPORBIT,
 CAM_TACTICAL,
 CAM_SHIPPOV,
 CAM_FARLOOK)
INSPACE_CAMERAS_MAIN = (CAM_SHIPPOV, CAM_SHIPORBIT, CAM_TACTICAL)
